### ISSUE TITLE
Make new release to help.sugarlabs.org

### ISSUE THREAD

**Issue by quozl** [godiard/help-activity#117]
help.sugarlabs.org page titles says it is for Sugar 0.118 but Sugar has released several versions since.

@chimosky, fyi.

**Comment by chimosky** [comment]
Fixed in #118.

**Comment by quozl** [comment]
Merged.  I do not recall how help.sugarlabs.org is updated.

**Comment by chimosky** [comment]
> Merged. I do not recall how help.sugarlabs.org is updated.

IIRC the docs are regenerated and deployed when they're changes to this repo, it currently reflects the change.

**Comment by quozl** [comment]
Yay, thanks.
