### ISSUE TITLE
Typing Turtle page missing details

### ISSUE THREAD

**Issue by vipulgupta2048** [godiard/help-activity#77]
The Typing Turtle help activity page (https://help.sugarlabs.org/en/typing_turtle.html) is missing the following the details:
1. GitHub repository Link  
2. Screenshots are linked to the activity page of old ASLO, but can be easily picked up from here (https://github.com/sugarlabs/typing-turtle-activity/tree/master/screenshots/en) for the help page.

**Comment by quozl** [comment]
Do we really need an issue for this?  Why not a pull request?  :grin:

**Comment by rdrsadhu** [comment]
> Do we really need an issue for this? Why not a pull request?

#78 

thanks :)
